create table accounts (
    id bigint generated by default as identity,
    number varchar(100),
    current_balance bigint
);

create table transactions (
    id bigint generated by default as identity,
    account_number varchar(100),
    amount bigint,
    datetime TIMESTAMP
)