create table accounts (
    account_id bigint generated by default as identity,
    account_number varchar(100),
    current_balance bigint
);

create table transactions (
    transaction_id bigint generated by default as identity,
    account_number varchar(100),
    transaction_amount bigint,
    transaction_datetime TIMESTAMP
)